@base_url = http://localhost:8080

@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxNDNlMGIxLTgwMDMtNGE2MS1iZDI3LTU1MmQ0Yjg5OTYxNiIsImVtYWlsIjoibGVvbmFyZG9AZW1haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0NDU4Mzg2NCwiZXhwIjoxNzQ0NjEyNjY0fQ.tyKVxPNwroHdJPZ2RIZUNnJbZf6oHhT_bVkebXjtfWA

@tokenNoAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NTY5NmIxLWIzNGQtNGViZC05MThhLTU5MzZmYzhlNTlkMiIsImVtYWlsIjoibWFyaWFAZW1haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ1ODM5ODQsImV4cCI6MTc0NDYxMjc4NH0.DT3X2Oh_NhAlMa9AOaE7kcN1osf5FdOFFhLTQnEMsDo

###
GET {{base_url}}/request-reversal
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

###

# SOLICITACAO DE ESTORNO - /request-reversal/:idTransaction

POST {{base_url}}/request-reversal/dc34f8a2-73bc-4e62-93de-68941ed28c13
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "description": "Envio para a conta errada, favor estornar"
}

###
#/request-reversal/pending/:idRequestReversal

PUT {{base_url}}/request-reversal/pending/062a5e03-4fad-4931-a58c-537f74dffd64
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}


###
# /request-reversal/reject/:idRequestReversal

PUT {{base_url}}/request-reversal/reject/062a5e03-4fad-4931-a58c-537f74dffd64
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}


###







