version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  db:
    container_name: postgres_group_ac
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app-network

  app:
    container_name: app_desafio
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    command: sh -c "npx prisma db pull && npx prisma generate && npm run dev"

volumes:
  postgres_data:
