@base_url = http://localhost:8080

@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxNDNlMGIxLTgwMDMtNGE2MS1iZDI3LTU1MmQ0Yjg5OTYxNiIsImVtYWlsIjoibGVvbmFyZG9AZW1haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0NDU4Mzg2NCwiZXhwIjoxNzQ0NjEyNjY0fQ.tyKVxPNwroHdJPZ2RIZUNnJbZf6oHhT_bVkebXjtfWA

@tokenNoAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NTY5NmIxLWIzNGQtNGViZC05MThhLTU5MzZmYzhlNTlkMiIsImVtYWlsIjoibWFyaWFAZW1haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ1ODM5ODQsImV4cCI6MTc0NDYxMjc4NH0.DT3X2Oh_NhAlMa9AOaE7kcN1osf5FdOFFhLTQnEMsDo

#BUSCAR TODOS OS USUARIOS
GET {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

###

# CRIAR  USUARIO 1
POST {{base_url}}/user
Content-Type: application/json

{
    "name": "Leonardo",
    "cpf": "098765432112",
    "email": "leonardo@email.com",
    "password": "pass1234",
    "admin": true
}

###

# CRIAR  USUARIO 2
POST {{base_url}}/user
Content-Type: application/json

{
    "name": "Maria",
    "cpf": "0987654343211",
    "email": "maria@email.com",
    "password": "pass@1234",
    "admin": false
}


