@base_url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzYzAzZWZjLTE5N2UtNGRkMy04YjgzLTM4Mzg3ZjQyZmZlMyIsImVtYWlsIjoibWFyaWFAZW1haWwuY29tIiwiaWF0IjoxNzQ0NTUzMjUwLCJleHAiOjE3NDQ1ODIwNTB9.pGkYXguRt2MuBZ4Asors0clAv4YKxGe0lNKu5HRR7aE


# BUSCAR CONTAS POR ID
GET {{base_url}}/account/22eb5561-5ec9-43e4-83ef-fdf666db6382
Content-Type: application/json
Authorization: Bearer {{token}}

###

# BUSCAR TODOS AS CONTAS
GET {{base_url}}/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

###

# CREDITAR UM VALOR NA CONTA
POST {{base_url}}/account/credit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "account_number": 12026547,
    "amount": 1000
}


