@base_url = http://localhost:8080

@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxNDNlMGIxLTgwMDMtNGE2MS1iZDI3LTU1MmQ0Yjg5OTYxNiIsImVtYWlsIjoibGVvbmFyZG9AZW1haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc0NDU4Mzg2NCwiZXhwIjoxNzQ0NjEyNjY0fQ.tyKVxPNwroHdJPZ2RIZUNnJbZf6oHhT_bVkebXjtfWA

@tokenNoAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2NTY5NmIxLWIzNGQtNGViZC05MThhLTU5MzZmYzhlNTlkMiIsImVtYWlsIjoibWFyaWFAZW1haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ1ODM5ODQsImV4cCI6MTc0NDYxMjc4NH0.DT3X2Oh_NhAlMa9AOaE7kcN1osf5FdOFFhLTQnEMsDo


# BUSCAR TODAS AS CONTAS
GET {{base_url}}/accounts
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

###

# BUSCAR TRANSACAO POR ACCOUNT_NUMBER
GET {{base_url}}/transaction/27945277
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

###

# FAZER TRANSACAO ENTRE CONTAS
POST {{base_url}}/transaction
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "amount": 400,
    "from_account_number": 27945277,
    "to_account_number": 83049750,
    "description": "Transferindo da conta 1 para a conta 2"
}

###

# REVERTER TRANSACAO
POST {{base_url}}/transaction/reversal/dc34f8a2-73bc-4e62-93de-68941ed28c13
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "requestId": "fe1ec982-13a6-43fd-82f2-493bb7ee0294"
}




