@base_url = http://localhost:8080


# CRIAR  USUARIO 1
POST {{base_url}}/user
Content-Type: application/json

{
    "name": "Leonardo",
    "cpf": "098765432112",
    "email": "leonardo@email.com",
    "password": "pass1234",
    "admin": true
}

###

# AUTENTICAR USUARIO ADMIN
POST {{base_url}}/login
Content-Type: application/json

{
    "email": "leonardo@email.com",
    "password": "pass1234"
}
###

# AUTENTICAR USUARIO NO ADMIN
POST {{base_url}}/login
Content-Type: application/json

{
    "email": "maria@email.com",
    "password": "pass@1234"
}
###



